### ISSUE TITLE
Example Site config.toml

### ISSUE THREAD

**Issue by ehaydenr** [digitalcraftsman/hugo-icarus-theme#27]
The config has "hugo-icarus-theme" as the theme, however the hugo themes [repo](https://github.com/spf13/hugoThemes) refers to this repo as "hugo-icarus". When cloning all repos at once, as specified in the [quickstart](https://gohugo.io/overview/quickstart/), the config file will need "hugo-icarus" to be the theme name.

**Comment by digitalcraftsman** [comment]
Hi @ehaydenr,

the hugoThemes repo added this theme as a submodule, but not under it's orignal name `hugo-icarus-theme`. 

If you clone all the submodules from hugoThemes they will be stored in the folder with the same of the submodule. Since they named the submodule of this theme `hugo-icarus` the theme will be saved in a folder with the same name.

Otherwise, if you clone this theme directly from this repo it will be saved with it's original name. The example config file can't know where you are cloning the theme. And that causes the different folder names and "wrong" theme name in the config. 

As you noticed, you only need to change the folder name for the theme.

**Comment by ehaydenr** [comment]
I understand how to run hugo with the theme. I created the issue more to let you know, if you weren't already aware, that the hugoThemes repo is referring to this repo in a way that might confuse first time users. It might be of interest to request that the submodule name be changed in the hugoThemes repo to `hugo-icarus-theme`

**Comment by digitalcraftsman** [comment]
I can understand your point of view. There are some others themes (exclude mine) whose submodule name doesn't equal the original repository. I don't know if their are any naming conventions. Give it a try and post an issue in the hugoThemes repository if you like.
