### ISSUE TITLE
Unable to find theme Directory

### ISSUE THREAD

**Issue by suntong** [digitalcraftsman/hugo-icarus-theme#5]
Hi, I'm following the instruction on https://github.com/digitalcraftsman/hugo-icarus-theme to setup my hugo based blog for the first time, and I think there is one step missing from the instruction.

I copied everything from `themes/hugo-icarus-theme/exampleSite/` into my root folders, changed the  `config.toml` config file, but when I run `hugo server --watch`, I got the error:

```
FATAL: 2015/11/30 Unable to find theme Directory: /path/git/blogs/themes/hugo-icarus-theme
```

I.e., I've already have the following files under my root folders:

```
 config.toml
 content/
 content/post/
 content/post/creating-a-new-theme.md
 content/post/migrate-from-jekyll.md
 content/post/hugo-is-for-lovers.md
 content/post/go-is-for-lovers.md
 content/post/introducing-icarus-and-its-features.md
 content/post/linked-post.md
 data/
 data/l10n.toml
 static/
 static/banners/
 static/banners/placeholder.png
```

what else should be put under `themes/hugo-icarus-theme`? 

Thanks

**Comment by digitalcraftsman** [comment]
Hello @suntong,

your setup of the root directories looks fine. Could it be possible that you downloaded the theme as zip file? Github usually appends the branch name to the zip file (e.g. hugo-icarus-theme-master.zip).

Even if it has other reasons, make sure that the theme folder under `themes` is named `hugo-icarus-theme`. Because this name was specified in the `config.toml` by default under `theme`.

If this doesn't work, could you provide future information of how your downloaded and setup the theme?

As a side note: it's not necessary to copy the content files. I just added them for the [demo](http://themes.gohugo.io/theme/hugo-icarus/) of this theme.

**Comment by suntong** [comment]
On Tue, Dec 1, 2015 at 3:32 AM, digitalcraftsman notifications@github.com
wrote:

> your setup of the root directories looks fine. Could it be possible that
> ...
> 
> Thanks a lot digitalcraftsman, I figured it out myself.

Describing in Linux command, here is what I did to get it properly
installed.

After having done git clone the theme,

```
 cd blogs/ # get into the root folder
 mkdir themes
 mv /path/git/hugo-icarus-theme/ themes/
 mv themes/hugo-icarus-theme/exampleSite/* .
 mv themes/hugo-icarus-theme/exampleSite/.gitignore .
 rmdir themes/hugo-icarus-theme/exampleSite/
```

> As a small note: it's not necessary to copy the content files. I just added
> them for the demo http://themes.gohugo.io/theme/hugo-icarus/ of this
> theme.

Yes I know, but I think they are very useful because I will have one less thing to figure out how to do, but can see results right a way. 

I'll sure remove them when I got mine setup correctly. 

Thanks again.
