### ISSUE TITLE
Creating Pages Instead Of Posts

### ISSUE THREAD

**Issue by jcgrav** [digitalcraftsman/hugo-icarus-theme#55]
I would like to create "pages" as opposed to "posts" that are displayed on the homepage. Is there an effective way to accomplish this?

My goal is to have pertinent pages in the header (about us, contact, etc).

**Comment by rasta-mouse** [comment]
@jcgrav instead of doing `hugo new post/name.md`, do `hugo new name.md`.
It will place `name.md` into `content` rather than `content\posts` and won't add it to post count or recent posts etc.  You can then add it to your menu by putting:
```
[[params.menu]]
    before = false
    label  = "Name"
    link   = "/name" 
```

into `config.toml`.

Or, use the `menu` parameter in `name.md` itself:

`menu = "main"`.

**Comment by digitalcraftsman** [comment]
Have a look at [this issue's comment](https://github.com/digitalcraftsman/hugo-icarus-theme/issues/22#issuecomment-302802712) which explains in more detail how this is solved in the upcoming version of this theme.
