### ISSUE TITLE
Display and Disqus config questions

### ISSUE THREAD

**Issue by suntong** [digitalcraftsman/hugo-icarus-theme#8]
Hi digitalcraftsman, 

Thanks for your excellent theme, blogging with Hugo to Github Pages is much easier than I was afraid. Now I have some few remaining issues, 
- The `gist` short-name does not seem to show correctly. Please take a look at my short demo at http://suntong.github.io/blogs/2015/12/05/wp2hugo/, in which `gist` code are showing strangely comparing to the actual gist: https://gist.github.com/suntong/0268a39d18bf3e684ff9
- The CSS is not perfect for code/programming blogging -- Please take a look at the [MarkdownTest source](https://raw.githubusercontent.com/suntong/blogs/master/content/post/MarkdownTest.md), and [its  result](http://suntong.github.io/blogs/2015/12/02/an-exhibit-of-markdown/), we can see that,
  - all inline-code, like `[more]`, `[delay +1 hour]`, are displayed incorrectly. 
  - The block quotes is unconventional as well, all other sites gmail, github or wordpress, show block quotes with that vertical bar at left. 
  - The Footnotes are displayed incorrectly, but I really don't care about this. Just letting you know instead. 

Also, I think I did Disqus configuration as documented, but I'm getting `We were unable to load Disqus`. My config.toml is still at the usual place. Could you take a look for me please?

Thanks

**Comment by suntong** [comment]
Oh, BTW, could you tell me where is the code that show banner image in the `RECENTS` column please? I am going to remove the picture icons from my site as I don't do/need those images. Thanks for your help.

**Comment by suntong** [comment]
Oh, another side question, The metadata section from your example looks like this:

```
+++
date = "2015-10-10T16:56:43+02:00"
title = "Introducing Icarus and it's features"
tags = ["theme", "hugo", "static sites"]
images = []
banner = "banners/placeholder.png"
categories = ["Lorem"]
+++
```

Which is different from the [official format](https://gohugo.io/tutorials/github-pages-blog/). Will the official format work for your Icarus template as well? 

The reason I'm asking is that [the official format looks nicely on github](https://github.com/srackham/stuarts-notes/blob/master/content/posts/2014-12-30-porting-my-blog-with-hugo.md), while [mine looks ugly](https://github.com/suntong/blogs/blob/master/content/post/Wp2Hugo.md). The metadata section shows up in nice table for the official format, but not mine.

**Comment by digitalcraftsman** [comment]
- Gists / inline codes / footnotes: It seems that MathJax,a javascript tool for displaying equations, tries interpret the Markdown as such. I'll take a look at it so that it doesn't break the design.
- Quotes: you're right, the formatting is a bit unconventional. I took  a look at the [orignal demo](http://blog.zhangruipeng.me/hexo-theme-icarus/2014/12/25/Markdown%20Example/) and saw the quotes with a nice styling. It also looks that the theme got a new stylings for smaller elements. I could  update the css file. 

---

Regarding Disqus: you've to register an account with your username. The script looks if the username exists. If not you'll see this error message. Replace it with an  existing username like "spf13" and it should work.

---

Regarding the recent articles widget: you can find the corresponding partial [here](https://github.com/digitalcraftsman/hugo-icarus-theme/blob/master/layouts/partials/widgets/recent_articles.html). It should be easy to remove the linked images. But if you remove them, you'll have a blank square and the title will still be indented.

---

The metadata section that you've is called [frontmatter](https://gohugo.io/content/front-matter/). By default Hugo inserts only the title and creation date. banner and categories are two variables that are known to Hugo for creating the tags and categories pages. But they aren't included by default.

I've added images and banner myself to add custom functionality. I've defined them in an [archetype file](https://gohugo.io/content/archetypes/). Archetypes are templates for blog posts (including the frontmatter). So you can create your own as you like. 

Therefore, could you explain what you mean with "official format"?

**Comment by suntong** [comment]
Thanks a lot for all you helps. All clear. 

Ah, for frontmatter, thanks for the link, I now know it _"supports a few different formats"_, and _"each with their own identifying tokens"_. What you have chosen is the TOML format, identified by `‘+++’`, and [what I have been refering to, the official format, from hugo tutorials](https://gohugo.io/tutorials/github-pages-blog/) uses YAML format, identified by `‘---’`. 

Github apparently doesn't understand TOML format, so shows them just as a long line of strings, yet it understands the YAML format, and [present it nicely as table ](https://github.com/srackham/stuarts-notes/blob/master/content/posts/2014-12-30-porting-my-blog-with-hugo.md).

I'll switch over to the YAML format so that my .md source will look good on Github as well.

**Comment by suntong** [comment]
BTW, if making MathJax cooperate with other turns out to be difficult, a viable option I can think of is to disable them site-wise by configuration in site `config.toml`, and enable it per article in frontmatter. 

Just a 2c thought.

**Comment by suntong** [comment]
Oh, did you have a chance to take a look for me for my Disqus configuration? 

I think I did Disqus configuration as documented, but I'm getting `We were unable to load Disqus` errors. My [config.toml](https://gist.github.com/suntong/2b529ce26099d6f26278) is still at the usual place, https://github.com/suntong/blogs/blob/master/config.toml. 

The doc says, _"Enter your shortname to enable the comment section under your posts"_, and I did that, but don't know why it wouldn't work. 

**Update**, my Disqus url is https://disqus.com/by/sfxpt/, so I used the id after the `@`, the `sfxpt` as the Disqus shortname, and it was not working. Thanks for the tip, I found out that I should use `Xpt`.

**Comment by suntong** [comment]
digitalcraftsman, I noticed another thing -- I found that the Icarus template is not showing the tags for the blogs.

They would normally show up as _"posted under tags, xxx, yyy, etc"_ in each blog post entry, but I didn't find them there in my post. 

Please take a look.

**Comment by digitalcraftsman** [comment]
Thanks for reporting this issues. Currently, I've not much time but I'll give you an update in the next days.

**Comment by suntong** [comment]
Yeah, I can tell. Thanks for the notification.
No rush. Get it right is more important than rush it fast.

**Comment by digitalcraftsman** [comment]
TODO:
- [x] update stylesheets
- [x] list tags in post header
- [x] Mathjax
  - [x] Gist shortcode
  - [x] inline code
  - [x] footnotes

In order to get Disqus running on your site you need to add your site to Disqus. Look [here](https://disqus.com/admin/create/) to do so.

**Comment by digitalcraftsman** [comment]
I've fixed the issues (except I missed one) with the changes in the latest commits.

**Comment by suntong** [comment]
Sorry for respond late. I wrapped up what I was doing ASAP and come back to this. 

Thanks for the fixes. That was amazing. Almost all things I reported are fixed. I've carefully went through everything again, and noted down the things not ideal. Here they are:
- "update stylesheets". Check! All reported things fixed.
- Gist shortcode. Check! The side effect now is that its current coloring theme make it very hard for normal none-decorated texts.  Please take at the gist code demo at http://suntong.github.io/blogs/2015/12/05/wp2hugo/. Moreover, the comment in the gist code, looks normal (just like plain text) when I'm viewing locally, using `hugo server --watch`, however, after I did `hugo -d dist` and publish the blog, I found that the comment from the gist code in http://suntong.github.io/blogs/2015/12/05/wp2hugo/ display strangely, i.e., they've been marked up. I don't know what is your intended result, but I hope it is the plain none-marked-up texts. 
- list tags in post header. Check! **Update**, fully working now, after my 3rd post. Don't know why it wasn't working as I've done nothing differently this time. Hmm..., Ahh, I know now, the one wasn't working was the old one, and `hugo -d dist` didn't rebuild it previously as nothing in its source changed. This time, I fixed my Disqus config and triggered a global rebuild. Hmm, should be the reason. 

So the only problem remains is Gist shortcode.

Thanks

**Comment by suntong** [comment]
Hi digitalcraftsman, 

Merry Christmas and happy new year!

Thanks again for this wonderful theme, hope you get some time continue working on it. 

Best Regards,

**Comment by suntong** [comment]
[patch.txt](https://github.com/digitalcraftsman/hugo-icarus-theme/files/72318/patch.txt)

I don't know css, but this hack seems to get it backs to normal, which might be overkill...

**Comment by digitalcraftsman** [comment]
Thanks @suntong. I wish you the same.

Currently, I'm trying to find the origin of the wrong Gist rendering. Which files exactly did you 'diffed' in the patch.txt?

**Comment by digitalcraftsman** [comment]
**Update:** before the update of the stylesheet everything looked fine. I don't know if this change also broke the layout of users how use Hexo and the original theme since I couldn't find a Hexo-based blog with embedded gists.

However, I just removed the CSS part that styled/broke the embedded gists. Now everything should work as expected. See 3cbdec5b8808a049f4bf03c2b121a61ef5df41e3

**Comment by suntong** [comment]
Thanks digitalcraftsman! Works fine now.
